languageCode = "en-us"
title = "code zilla"
baseURL = "http://yiou.me/blog"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "code-z"

[taxonomies]
tag = "tags"
category = "categories"

[params]
  subtitle = "Front-end, Game Dev and Scribbles"
  #logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "Yiou Chen"
  email = "chen.yiou1992@gmail.com"
  github = "yiochen"
  linkedin = "yiouchen"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "Portfolio"
    url = "http://yiou.me"
    weight = 3