languageCode = "en-us"
title = "code zilla"
baseURL = "http://yiou.me/blog"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"

[taxonomies]
tag = "tags"
category = "categories"

[params]
  subtitle = "Build a beautiful and simple website in minutes"
  #logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "Yiou Chen"
  email = "chen.yiou1992@gmail.com"
  github = "yiochen"
  linkedin = "yiochen"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3